### ISSUE TITLE
Issue with latest release 8.21.0 using SAML option

### ISSUE THREAD

**Issue by gondor** [getsentry/sentry-auth-saml2#16]
I know this is experimental still but figured reporting may help the team in testing and resolution.  When trying to setup SAML to test with the latest release the follow exception occurred.  Let me know if you want the full RAW json of the event from Sentry.

![sentry-template-error-saml](https://user-images.githubusercontent.com/148656/31513349-face3896-af42-11e7-92d5-d71fb8150cf1.png)

**Comment by mattrobenolt** [comment]
This is all heavily in development and not ready for other consumers yet. :) If you want to use this, you'd need to pair with master of sentry codebase and master of this repository otherwise there will be things wrong. But this isn't a problem with current masters.

**Comment by gondor** [comment]
Ok, thank you for the info
