### ISSUE TITLE
Beta Testing

### ISSUE THREAD

**Issue by gondor** [getsentry/sentry-auth-saml2#2]
Could really use this plugin and was attempting to be a beta tester.  I have added it to Sentry via `pip install https://github.com/getsentry/sentry-auth-saml2/archive/master.zip` and it installs successfully but I don't see it in the `Auth` page.  It says there are no providers to be found.

Any tricks?

**Comment by mattrobenolt** [comment]
It's disabled behind a switch.

Add `SENTRY_FEATURES['organizations:saml2'] = True` into your sentry.conf.py. You also need sentry 8.20.0. More stuff is being added into 8.21.0 yet, so functionality may be slightly limited as this is under active development.

**Comment by gondor** [comment]
Awesome thanks.  I'm on 8.20.0 right now and have this running in Swarm so it's easy to upgrade.  Thank you for the fast response
