### ISSUE TITLE
saml2 generic metadata

### ISSUE THREAD

**Issue by lyandr** [getsentry/sentry-auth-saml2#30]
Hello,

i installed the sentry-auth-saml2 on my onpremise Sentry. I know have the diffrents providers but i didn't find an endpoint in order to have saml metadata of sentry.

Is there any endpoint? I've tried /saml/metatdata/<organization> but i have the following message: The organization does not exist or does not have SAML SSO enabled.

Did i miss something?

Regards

**Comment by martinalig** [comment]
Hi, 

the URLs are:
- https://yourdomain.com/saml/metadata/yourorganization/
- https://yourdomain.com/saml/acs/yourorganization/

but you first need to enable SAML in Organization Settings -> Auth
