### ISSUE TITLE
Support for 9.0?

### ISSUE THREAD

**Issue by MikeBairdRocks** [getsentry/sentry-auth-saml2#34]
Adding this to the requirements.txt for the [Docker compose ](https://github.com/getsentry/onpremise) onbuild fails with error:
`Could not find xmlsec1 config. Are libxmlsec1-dev and pkg-config installed?`

So my question is, does this work with 9.0? If so, what am I doing wrong. 

I'm adding [the master.zip](https://github.com/getsentry/sentry-auth-saml2/archive/master.zip) to `requirements.txt` and running `docker-compose build`. I also tried to setup sentry on an ubunutu server and I ran `pip install https://github.com/getsentry/sentry-auth-saml2/archive/master.zip`  with the same error.

**Comment by evanpurkhiser** [comment]
Hi @MikeBairdRocks, the docker image is missing the `libxmlsec1-dev` and `pkg-config` package. I've added it to our docker build here https://github.com/getsentry/docker-sentry/pull/147 so it should now work once the docker image rebuilds.
