### ISSUE TITLE
saml2 with MS Azure

### ISSUE THREAD

**Issue by brogger71** [getsentry/sentry-auth-saml2#35]
Hello,

I used the generic SAML2 module to connect our on-premise deployment with MS Azure AD. I can use the Metadata provided by Microsoft, but it's not clear to me, which replay URLs i have to provide.
In the sentry.io docu i read, that the following URLs are to be used for the Cloud deployment:

ACS: https://sentry.io/saml/acs/{organization_slug}/
SLS: https://sentry.io/saml/SLS/{organization_slug}/
Metadata: https://sentry.io/saml/metadata/{organization_slug}/

I adapted them to our deployment but it didn't work.
Any ideas?

Thanks,
Michael

**Comment by evanpurkhiser** [comment]
@ndmanvar have you used MS Azure AD before? I seem to recall us fiddling with this at one point

**Comment by brogger71** [comment]
@EvanPurkhiser can you point me in a direction so i can investigate further?

Thanks

**Comment by evanpurkhiser** [comment]
Would you be able to describe more about what exactly didn’t work? How did you map your attributes?

**Comment by ndmanvar** [comment]
![saml-azure-adfs](https://user-images.githubusercontent.com/314061/47887217-6c66b400-ddfb-11e8-9bba-427f75f2d5ce.gif)

Yep, @EvanPurkhiser

**Comment by brogger71** [comment]
@ndmanvar your vid was extremly helpful, thank you! I could succesfully config SAML2 with MS Azure AD. But mistakenly i linked my personal account with the sentry admin account while config SAML2. Is there an easy way to SSO unlink accounts?

**Comment by ndmanvar** [comment]
@brogger71 glad you found the GIF useful!

The best/easiest way is to remove SSO/SAML2 and reconfigure it with the appropriate account (non-personal).
Hope that helps.
