### ISSUE TITLE
SAML2 metadata upfront

### ISSUE THREAD

**Issue by dsanader** [getsentry/sentry-auth-saml2#36]
Hello,

Registering Sentry as Service Provider inside [LemondLDAP::NG](https://lemonldap-ng.org/documentation/latest/idpsaml) requires to upload SP metadata.

But, It seems I can't easily get Sentry's SP metadata until I've fully setup SAML2. Visiting https://mysentry.example.com/saml/metadata/myorg/ I get `The organization does not exist or does not have SAML SSO enabled`.

I guess I could try to generate the required XML based on other examples, but that seems rather painful. Do you have a better idea to exit that loop ?

The other apps I've setup are providing either an XML generation link or a working URL.

**Comment by evanpurkhiser** [comment]
Hi @dsanader, I've heard a number of people ask for this. I think this is reasonable so I've added this here https://github.com/getsentry/sentry/pull/10312
