### ISSUE TITLE
The last (october 2019) commit breaks compatibility with Sentry 9.1.2

### ISSUE THREAD

**Issue by trondhindenes** [getsentry/sentry-auth-saml2#43]
We just experienced issues with Sentry after rebuilding the container we run it out of. It seems that 386078ef1e7a75f1e37b797e153492b48d9c5886 breaks compatibility with Sentry 9.1.2.

Our workaround in the Docker img:
```
# Suspect broken
#RUN pip install https://github.com/getsentry/sentry-auth-saml2/archive/master.zip
RUN pip install https://github.com/getsentry/sentry-auth-saml2/archive/efb12e050a829eb2287bec0df8aac9ece4b0545d.zip
```

**Comment by myonlylonely** [comment]
> We just experienced issues with Sentry after rebuilding the container we run it out of. It seems that [386078e](https://github.com/getsentry/sentry-auth-saml2/commit/386078ef1e7a75f1e37b797e153492b48d9c5886) breaks compatibility with Sentry 9.1.2.
> 
> Our workaround in the Docker img:
> 
> ```
> # Suspect broken
> #RUN pip install https://github.com/getsentry/sentry-auth-saml2/archive/master.zip
> RUN pip install https://github.com/getsentry/sentry-auth-saml2/archive/efb12e050a829eb2287bec0df8aac9ece4b0545d.zip
> ```

Thank you! That solved my problem.

**Comment by joshuarli** [comment]
https://github.com/getsentry/sentry-auth-saml2/issues/44#issuecomment-548964160

**Comment by joshuarli** [comment]
@trondhindenes @myonlylonely This should be fixed in https://github.com/getsentry/sentry-auth-saml2/pull/46, so sorry for the delay. Once it lands in master, you should be able to install from master again.
