### ISSUE TITLE
error with from django.forms.util import ErrorList

### ISSUE THREAD

**Issue by Uporaba1** [getsentry/sentry-auth-saml2#44]
There was a problem when adding the **sentry-auth-saml2** module through the command specified in the documentation: `pip install https://github.com/getsentry/sentry-auth-saml2/archive/master.zip`

after installing the module, the sentry crashed with an error:
![image](https://user-images.githubusercontent.com/32709525/68007248-d29b4680-fc9c-11e9-96f0-19d2d9555fe7.png)
```
File "/usr/local/lib/python2.7/site-packages/sentry_auth_saml2/forms.py", line 4, in <module>
from django.forms.utils import ErrorList
ImportError: no module named utils
```
In file **sentry_auth_saml2 / forms.py** need to change: `django.forms.utils import ErrorList` on `django.forms.util import ErrorList`

After change:
![image](https://user-images.githubusercontent.com/32709525/68007326-11310100-fc9d-11e9-8026-8b9476aede37.png)

[You broke it 22 days ago](https://github.com/getsentry/sentry-auth-saml2/commit/386078ef1e7a75f1e37b797e153492b48d9c5886). I created a pull request to fix this error.

**Comment by Uporaba1** [comment]
@joshuarli can u fix it pls?

**Comment by joshuarli** [comment]
`master`'s being made compatible with Django 1.9, which sentry master will be on soon. I should have done it in a backwards compatible manner though. For now, you can just install `https://github.com/getsentry/sentry-auth-saml2/archive/e519afe24bfc8778ca7797a1878a62bff4b29dfd.zip` which doesn't have those changes.

I won't be changing it to be backwards compatible; we're going to be moving these external plugin repositories into sentry very soon anyways.

**Comment by mbarrien** [comment]
For people running the open source version, does this mean we'll be seeing a tagged version of Sentry 10.0 soon, or are we expected to install from HEAD of sentry master (with the corresponding lack of documentation)?

Having this barely documented workaround for people running from the most recently tagged Sentry would be a poor user experience. At the minimum this should be mentioned in the README for people running/installing Sentry 9.1.2.

**Comment by joshuarli** [comment]
@mbarrien I looked into this more and turns out Sentry 9.1.2 is running on Django 1.6 - keeping backwards compat for that version of Django totally went over my head, haha. So sorry about that. You're right that that workaround is a poor user experience; fIxed in https://github.com/getsentry/sentry-auth-saml2/pull/46.

**Comment by mbarrien** [comment]
Thanks for restoring the backwards compatibility! Would be even more excited if there was an update announced about https://forum.sentry.io/t/when-will-a-new-version-be-tagged-for-sentry-open-source/5622 for Sentry 10.0!

**Comment by joshuarli** [comment]
I'd guess at the very latest, by december :) Stay tuned.
